=begin
#Lago API documentation

#Lago API allows your application to push customer information and metrics (events) from your application to the billing application.

The version of the OpenAPI document: 0.46.1-beta
Contact: tech@getlago.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LagoAPI::EventInputEventProperties
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LagoAPI::EventInputEventProperties do
  let(:instance) { LagoAPI::EventInputEventProperties.new }

  describe 'test an instance of EventInputEventProperties' do
    it 'should create an instance of EventInputEventProperties' do
      expect(instance).to be_instance_of(LagoAPI::EventInputEventProperties)
    end
  end
  describe 'test attribute "operation_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["add", "remove"])
      # validator.allowable_values.each do |value|
      #   expect { instance.operation_type = value }.not_to raise_error
      # end
    end
  end

end
